### ISSUE TITLE
Maternal pre-pregnant BMI: data validation

### ISSUE THREAD

**Issue by dlemas** [lemaslab/BEACH-reports#19]
Please interrogate the data entry related to pre-pregnant BMI for BEACH participants that includes mom-baby.

@michele-himadi - please identify participants that need to be checked/imported, and create a 
comment with list of participants using the example below. 

**Final Prepregnant BMI: BEACH Study Overview (report)/ beach)final_BMI(variable)**

- [x] BLS012A
- [x] BLS013A
- [x] BLS014A
- [x] BLS016A
- [x] BLS019A
- [x] BLS020A

**Comment by dlemas** [comment]
@bryannamirabal - please include some notes on this issue. If you have completed the validation, please close the issue with a comment.

**Comment by bryannamirabal** [comment]
This validation was completed.
