### ISSUE TITLE
Enrollment Report: data extraction

### ISSUE THREAD

**Issue by dlemas** [lemaslab/BEACH-reports#2]
Please extract the data within the "BEACH Study Overview" report that is stored within Redcap. 

Script: [get_reportData_21221.Rmd](https://github.com/lemaslab/BEACH-reports/blob/master/code/get_data/get_reportData_21221.Rmd)

This script requires:

- access to BEACH study RedCap project via API token
- R/rstudio configuration using the keyringr package
- UF VPN access

This script will output:

- data as an *.Rdata object locally within the directory ~/data/processed/

**Comment by michele-himadi** [comment]
I'm able to run the code and extract the data

**Comment by dlemas** [comment]
This issue can be closed when all team members can pull the data: @xkcococo @michele-himadi @Decicco-Lewis 

Please comment when you can pull data.

**Comment by dlemas** [comment]
this has been resolved.
