### ISSUE TITLE
Table 1: pull data

### ISSUE THREAD

**Issue by dlemas** [lemaslab/BEACH-reports#25]
This issue is complete when you have a redcap report with all variables for Table 1.

**Comment by michele-himadi** [comment]
The following data has been pulled:
- maternal age (using maternal birthdate and date of infant birth)
- gestational age
- breastfeeding 
- BMI/BMI groups to sort mothers by
https://github.com/lemaslab/BEACH-reports/blob/michele/code/get/get_RedCapData_36804.Rmd
