### ISSUE TITLE
Enrollment Report: data validation

### ISSUE THREAD

**Issue by dlemas** [lemaslab/BEACH-reports#3]
Please interrogate the data entry related to race/ethnicity/gender for BEACH participants that includes mom-baby. 

**MATERNAL ETHNICITY: BEACH Study Overview (report)/ mom_ethnicity_nih (variable)**

- [x] BLS098A
- [x] BLS099A
- [x] BLS100A
- [x] BLS101A
- [x] BLS104A
- [x] BLS114A
- [x] BLS115A
- [x] BLS117A
- [x] BLS118A
- [x] BLS119A
- [x] BLS121A

**MATERNAL SEX: BEACH Study Overview (report)/ maternal_sex_nih (variable)**

- [x] BLS110A
- [x] BLS111A
- [x] BLS112A
- [x] BLS113A
- [x] BLS114A
- [x] BLS115A
- [x] BLS117A
- [x] BLS118A
- [x] BLS119A
- [x] BLS121A

**INFANT SEX: BEACH Study Overview (report)/ infant_sex_nih (variable)**

- [x] BLS100A
- [x] BLS103A
- [x] BLS114A
- [x] BLS115A
- [x] BLS117A
- [x] BLS118A
- [x] BLS119A
- [x] BLS121A
[20220907_missing_race.csv](https://github.com/lemaslab/BEACH-reports/files/9559437/20220907_missing_race.csv)

**Comment by michele-himadi** [comment]
@Decicco-Lewis will start working on BLS098-110 and I will wrap up entering some recently found missing files and start on BLS111 (and update after)

**Comment by Decicco-Lewis** [comment]
The data for the listed participants for those categories are entered. Please let me know if there are any questions.

**Comment by michele-himadi** [comment]
Ran code and no fields marked as N/A in report. Should be good.

**Comment by dlemas** [comment]
this issue has been resolved.
